---
# vars file for openbao

user: 1000

image:
  registry: quay.io/openbao/openbao
  tag: 2.1.1

config:
  path: /containers_vols/openbao

storage:
  host:
    data: /containers_vols/openbao/data
  
  container:
    data: /openbao/data

certs:
  host:
    private_key_path: /containers_vols/openbao/certs/private.key
    certificate_path: /containers_vols/openbao/certs/certificate.pem

  container:
    certificate_path: /openbao/certs/certificate.pem
    private_key_path: /openbao/certs/private.key
    caCertificate: /openbao/certs/ca.pem