---

- name: Ensure the latest version of podman is present
  ansible.builtin.dnf:
    name: podman
    state: latest

- name: Ensure the data dir is present
  ansible.builtin.file:
    path: "{{ config.path }}/certs"
    state: directory
    mode: '0755'

- name: Ensure OpenBao configuration is present
  ansible.builtin.template:
    src: config.hcl.j2
    dest: "{{ config.path }}/config.hcl"
    mode: u=rw,g=r,o=r

- name: Ensure private key are copied
  ansible.builtin.copy:
    src: "{{ certs.localhost.private_key_path }}"
    dest: "{{ certs.host.private_key_path }}"

- name: Ensure certificate are copied
  ansible.builtin.copy:
    src: "{{ certs.localhost.certificate_path }}"
    dest: "{{ certs.host.certificate_path }}"

- name: Ensure OpenBao pod is present
  containers.podman.podman_container:
    name: openbao-server
    image: "{{ image.registry }}:{{ image.tag }}"
    volume:
      - "{{ config.path }}/config.hcl:/etc/bao/config/config.hcl:z"
      - "{{ certs.host.certificate_path }}:{{ certs.container.certificate_path }}:z"
      - "{{ certs.host.private_key_path }}:{{ certs.container.private_key_path }}:z"
    expose:
      - 8200
    ports:
      - "8200:8200"