---

- name: Ensure the latest version of podman is present
  become: true
  ansible.builtin.dnf:
    name: podman
    state: latest

- name: Ensure the data dir is present
  become: true
  loop:
    - "{{ config.path }}/certs"
    - "{{ storage.host.data }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Ensure OpenBao configuration is present
  ansible.builtin.template:
    src: config.hcl.j2
    dest: "{{ config.path }}/config.hcl"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Ensure host file is present
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: u=rw,g=r,o=r

- name: Ensure private key and certificate are copied
  loop:
    - { "src" : "{{ certs.localhost.private_key_path }}", "dest" : "{{ certs.host.private_key_path }}" }
    - { "src" : "{{ certs.localhost.certificate_path }}", "dest" : "{{ certs.host.certificate_path }}" }
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 777

- name: Ensure OpenBao pod is present
  containers.podman.podman_container:
    name: openbao
    image: "{{ image.registry }}:{{ image.tag }}"
    command: "bao server -config=/openbao/config/config.hcl"
    user: "{{ user }}"
    volume:
      - "{{ config.path }}/config.hcl:/openbao/config/config.hcl:z"
      - "{{ certs.host.certificate_path }}:{{ certs.container.certificate_path }}:Z"
      - "{{ certs.host.private_key_path }}:{{ certs.container.private_key_path }}:Z"
      - "{{ storage.host.data }}:{{ storage.container.data }}:Z"
    ports:
      - "8200:8200"
      - "8201:8201"
      - "8202:8202"