galaxy_info:
  author: Alessandro Bitocchi
  description: openbao install role
  company: Sourcesense

  license: GPL

  min_ansible_version: 2.1

  platforms:
  - name: Almalinux
    versions:
    - 9.5.20241203

